---
harbor_cert_key: "{{harbor_data_volume}}/key.pem"
harbor_cert: "{{harbor_data_volume}}/cert.pem"
harbor_data_volume: "/srv/docker/harbor/data"
harbor_hostdir: /srv/docker/harbor/current
harbor_versioned_hostdir: "/srv/docker/harbor/{{harbor_version}}"
harbor_volumes:
- "{{harbor_hostdir}}"
harbor_pre_version: '{{harbor_pre_versions[harbor_version]|default("{0}.{1}".format(
  harbor_version[:1],
  (((harbor_version[2:]|float)-0.1)|string)))}}'
harbor_version: 2.3.1
harbor_pre_versions:
  2.3.0: 2.2.9
harbor_installer_url: "https://github.com/goharbor/harbor/releases/download/v2.3.1/harbor-online-installer-v{{harbor_version}}.tgz"
harbor_installer_dir: "{{harbor_versioned_hostdir}}/installer"
harbor_image: "vaultwarden/server:1.21.0"
harbor_install_args: "--with-notary --with-chartmuseum"
harbor_network: 172.34.0
harbor_chart_url: disabled
harbor_domain: harbor.foo.net
harbor_github_token: null
harbor_password: xxxtR7487913189781az
harbor_db_password: xxxtR0xN0eQ9oP1tQ2w
#
harbor_pg: "13"
harbor_backup_image: corpusops/dbsmartbackup:postgres-{{harbor_pg}}
harbor_xforwarded: true
harbor_compose_project: "{{harbor_hostdir|copsf_basename}}"
harbor_ip: 127.0.0.1
harbor_f2b_ports: "{{harbor_public_http_port}},{{harbor_public_https_port}} "
harbor_public_http_port: 80
harbor_public_https_port: 443
harbor_http_port: 8080
harbor_hosts: ["{{harbor_domain}}"]
harbor_app_service_config_files: []
harbor_db_name: db
harbor_db_host: postgresql
harbor_db_port: 5432
# do not change this unless you use external database
harbor_db_user: postgres
harbor_riot_theme:  dark
harbor_compose_files: [docker-compose.yml, docker-compose-prod.yml]
harbor_dbs_compression: nocomp
harbor_docker_dot_env: |-
  # ansible managed
  HARBOR_NETWORK={{harbor_network}}
  NGINX_REAL_IP_FROM={{harbor_real_ip_from}}
  COMPOSE_PROJECT_NAME={{harbor_compose_project}}
  CONTROL_COMPOSE_FILES={{harbor_compose_files|join(' ')}}
  COMPOSE_FILE={{harbor_compose_files|join(':')}}
  DATA_FOLDER=/data
  DATABASE_URL=postgresql://{{harbor_db_user}}:{{harbor_db_password}}@{{harbor_db_host}}:{{harbor_db_port}}/{{harbor_db_name}}
  POSTGRES_USER={{harbor_db_user}}
  POSTGRES_PASSWORD={{harbor_db_password}}
  POSTGRES_HOST={{harbor_db_host}}
  POSTGRES_PORT={{harbor_db_port}}
  POSTGRES_DB={{harbor_db_name}}
  PGPASSWD={{harbor_db_password}}
  PGPASSWORD={{harbor_db_password}}
  HARBOR_DBS_COMPRESSION={{harbor_dbs_compression}}
  HARBOR_KEEP_DUMPS={{harbor_keep_dumps}}
  HARBOR_BACKUP_IMAGE={{harbor_backup_image}}
  HARBOR_DB_NAMES=all
  F2B_LOG_LEVEL={{harbor_f2b_loglevel}}
  LOG_FILE={{harbor_log_file}}
  LOG_LEVEL={{harbor_log_level}}
  F2B_TIMER=30
  {% if harbor_smtp_host %}
  SMTP_FROM={{harbor_smtp_from}}
  SMTP_FROM_NAME={{harbor_smtp_from_name}}
  SMTP_TIMEOUT={{harbor_smtp_timeout}}
  SMTP_HOST={{harbor_smtp_host}}
  SMTP_PORT={{harbor_smtp_port}}
  SMTP_SSL={{harbor_smtp_ssl}}
  SMTP_EXPLICIT_TLS={{harbor_smtp_explicit_tls}}
  SMTP_USERNAME={{harbor_smtp_username}}
  SMTP_PASSWORD={{harbor_smtp_password}}
  {% endif %}
  SMTP_TIMEOUT={{harbor_smtp_timeout}}
  HARBOR_RESTART_POLICY={{harbor_restart_policy}}
# https://github.com/harbor/jslib/issues/52
# https://github.com/dani-garcia/harbor/issues/1166
# cannot be set higher globally, only by users by their vault settings, but we should in the future.
# https://github.com/harbor/jslib/issues/52
harbor_sheme: https
harbor_default_is: [harbor.org, vector.im]
harbor_real_ip_from: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 {{harbor_network}}.0/12"
harbor_keep_dumps: "1"
harbor_restart_policy: unless-stopped
harbor_listen_if: 0.0.0.0
harbor_listen_int_if: 127.0.0.1
harbor_dcompose: docker-compose -p {{harbor_compose_project}}
harbor_traefik_extra: ""
harbor_stopped_state: stopped
harbor_started_state: started
harbor_stdout: /dev/null
harbor_stderr: /dev/null
harbor_signups_allowed: True
harbor_smtp_from: ""
harbor_smtp_from_name: harbor
harbor_smtp_host: ""
harbor_smtp_port: 465
harbor_smtp_ssl: "true"
harbor_smtp_explicit_tls: "true"
harbor_smtp_username: ""
harbor_smtp_password: ""
harbor_smtp_timeout: 15
# random 40char+ string
harbor_logs_dir: /var/log/harbor
harbor_log_file: "{{harbor_logs_dir}}/harbor.log"
harbor_log_level: info
harbor_job_workers: 10
harbor_job_retries: 10
harbor_fail2ban_retries: 10
harbor_fail2ban_bantime: 14400
harbor_f2b_loglevel: INFO
harbor_allow_admin_api_ips: []
harbor_rotate_size: 200M
harbor_rotate_count: 50
# 0 deny, 1 allow
# harbor_allow_admin_api_ips: [x.x.x.x 1]
harbor_db_max_idle_conns: 100
harbor_db_max_open_conns: 900
harbor_f2b_tz: "Europe/Paris"
harbor_force_sync_ssh_user: null
harbor_sync_ssh_user: ""
harbor_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
  {% if((harbor_force_sync_ssh_user) or
        (harbor_sync_ssh_user and (harbor_force_sync_ssh_user == True))
    )%}
  {% set user = harbor_sync_ssh_user or ansible_user or '' %}
  {% if user %}-l {{user}}{% endif %}
  {% endif %}
harbor_code_rsync_opts: ["-aAHzv"]
