- stat: {dest: "{{harbor_hostdir}}/harbor.yml"}
  register: harborcfg
- template:
    src: "setup/{{item}}"
    dest: "{{harbor_hostdir}}/{{item}}"
    trim_blocks: false
    force: true
  loop: [harbor.yml]
  when: not harborcfg.stat.exists

- template:
    src: "setup/{{item}}"
    dest: "{{harbor_hostdir}}/{{item}}"
    trim_blocks: false
    mode: "0750"
    force: true
  loop: [wrap_prepare, fix.sh]

- shell: "{{harbor_hostdir}}/wrap_prepare"
