#!/usr/bin/env bash
set -ex
cd $(dirname $(readlink -f "$0"))
if [[ -z ${SKIP_PREPARE-} ]];then
    ./prepare {{harbor_install_args}}
fi
if [ -e docker-compose.yml ];then
  sed -i -r \
  -e "s/ ( - (80:8080))/#\1/g" \
  docker-compose.yml
fi
# vim:set et sts=4 ts=4 tw=0:
